# Generated by Django 5.2.1 on 2025-05-26 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1, verbose_name='Porte')),
                ('idade_aproximada', models.PositiveIntegerField(help_text='Idade em anos', verbose_name='Idade')),
                ('caracteristicas', models.TextField(blank=True, help_text='Características especiais, personalidade, etc.', verbose_name='Características')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/', verbose_name='Foto')),
                ('microchip', models.CharField(blank=True, max_length=50, verbose_name='Microchip')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
            },
        ),
        migrations.CreateModel(
            name='AnimalPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('cancelado', 'Cancelado')], default='perdido', max_length=20, verbose_name='Status')),
                ('data_perda', models.DateTimeField(verbose_name='Data da Perda')),
                ('local_perda', models.CharField(help_text='Local onde foi visto pela última vez', max_length=200, verbose_name='Local da Perda')),
                ('descricao', models.TextField(help_text='Circunstâncias da perda, comportamento do animal, etc.', verbose_name='Descrição')),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Recompensa')),
                ('contato_emergencia', models.CharField(blank=True, max_length=100, verbose_name='Contato de Emergência')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdidos', to='pets.animal')),
            ],
            options={
                'verbose_name': 'Animal Perdido',
                'verbose_name_plural': 'Animais Perdidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avistamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('data_avistamento', models.DateTimeField(verbose_name='Data do Avistamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avistamentos/', verbose_name='Foto')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal_perdido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamentos', to='pets.animalperdido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avistamento',
                'verbose_name_plural': 'Avistamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residencia', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('cobertura', 'Cobertura'), ('loft', 'Loft')], default='apartamento', max_length=20, verbose_name='Tipo de Residência')),
                ('numero_residencia', models.CharField(help_text='Número do apartamento/casa', max_length=10, verbose_name='Número')),
                ('apartamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartamento (Antigo)')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto do Perfil')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.condominio', verbose_name='Condomínio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='pets.morador'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('animal_perdido', 'Animal Perdido'), ('avistamento', 'Avistamento'), ('encontrado', 'Animal Encontrado')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
